// @zarya/db — Schémas Drizzle ORM, client DB, migrations

// Opérateurs de requête drizzle ré-exportés (le package db possède l'ORM).
export { and, eq } from "drizzle-orm";
export type { DbForCabinet } from "./client";
export { db, getDbForCabinet } from "./client";
// Schémas et enums
export {
  adresse,
  cabinet,
  cabinetMembre,
  cabinetStatutEnum,
  calendarCabinetConfig,
  calendarSchema,
  canalRelanceEnum,
  categorieDocumentEnum,
  client,
  contact,
  crmSchema,
  docSchema,
  document,
  echeance,
  extractionContextEnum,
  extractionInputTypeEnum,
  extractionSchema,
  extractionStatusEnum,
  fichierPhysique,
  frequenceEcheanceEnum,
  frequenceServiceEnum,
  invitationMembre,
  invocation,
  langueEnum,
  logicielComptableEnum,
  modeleRelance,
  modeTransmissionEnum,
  paramComptable,
  pauseClient,
  planTarifaireEnum,
  politiqueRelanceEnum,
  propositionClassement,
  relance,
  roleMembreEnum,
  service,
  sessionOnboardingFiduciaire,
  sourceIngestionEnum,
  statutClassementEnum,
  statutClientEnum,
  statutEcheanceEnum,
  statutInvitationMembreEnum,
  statutRelanceEnum,
  statutSessionOnboardingFiduciaireEnum,
  statutTraitementEnum,
  templateEcheance,
  typeAdresseEnum,
  typeEcheanceEnum,
  typeServiceEnum,
  uploadBrut,
  zefixRechercheCabinet,
} from "./schema";
