// @zarya/integrations — wrappers : Infomaniak AI (souveraineté CH), Zefix, …
// (Bedrock/Mistral retirés de la chaîne IA, cf. ADR 0010.)

export type {
  IkChatCompletionParams,
  IkChatCompletionResponse,
  IkChatContentPart,
  IkChatMessage,
  IkChatResponseMessage,
  IkChatRole,
  IkEmbeddingData,
  IkEmbeddingsParams,
  IkEmbeddingsResponse,
  IkJsonSchema,
  IkModel,
  IkModelsResponse,
  IkResponseFormat,
  IkUsage,
  InfomaniakClientOptions,
  InfomaniakErrorCode,
  ModelCategory,
} from "./infomaniak";
export {
  InfomaniakClient,
  InfomaniakError,
  infomaniakClient,
} from "./infomaniak";
export type {
  CalendarEvent,
  CreateEmailSubscriptionOptions,
  CreateEventParams,
  DetectTenantRegionOptions,
  EmailDetail,
  EmailFilter,
  EmailSubscriptionResult,
  EmailSummary,
  EventFilter,
  ExpiringSubscription,
  GraphNotification,
  IngestNotificationOptions,
  IngestStatus,
  MicrosoftErrorCode,
  MicrosoftGraphActeur,
  MicrosoftGraphClientOptions,
  MicrosoftIntegrationParams,
  MicrosoftIntegrationStatus,
  MicrosoftIntegrationStatut,
  MicrosoftOAuthConfig,
  MicrosoftOAuthStatePayload,
  MicrosoftTokenResponse,
  MicrosoftTokenSet,
  RenewSubscriptionsOptions,
  RenewSubscriptionsResult,
  SendCabinetEmailOptions,
  SendCabinetEmailParams,
  SendCabinetEmailTrackedOptions,
  SendCabinetEmailTrackedOutcome,
  SendEmailOutcome,
  SendEmailParams,
  SubscriptionLookup,
  TenantRegionResult,
  TenantRegionSignal,
  TenantRegionSource,
  TenantRegionVerdict,
} from "./microsoft";
export {
  acknowledgeTenantRegion,
  applySignature,
  archiveMicrosoftIntegration,
  buildAuthorizationUrl,
  classifyTenantRegion,
  createEmailSubscription,
  detectAndPersistTenantRegion,
  exchangeCodeForTokens,
  findSubscriptionByGraphId,
  getMicrosoftIntegrationStatus,
  getMicrosoftOAuthConfig,
  getValidMicrosoftAccessToken,
  ingestEmailNotification,
  isAccessTokenExpiring,
  listExpiringSubscriptions,
  loadMicrosoftTokens,
  MICROSOFT_SCOPES,
  MicrosoftGraphClient,
  MicrosoftGraphError,
  markSubscriptionError,
  parseGraphNotifications,
  REFRESH_MARGIN_MS,
  refreshAccessToken,
  renewExpiringSubscriptions,
  saveEmailSubscription,
  saveMicrosoftTokens,
  saveTenantRegionVerdict,
  sendCabinetEmail,
  sendCabinetEmailTracked,
  signOAuthState,
  updateSubscriptionExpiration,
  upsertEmailBrut,
  verifyOAuthState,
} from "./microsoft";
export type { ZefixAddress, ZefixCompanyDetail, ZefixCompanySummary, ZefixResultat } from "./zefix";
export { ZefixClient, ZefixError, zefixClient } from "./zefix";
